#!/bin/bash

source_dir=~/source/josm

echo "Überprüfe ob Verzeichnis für JOSM SVN-Version existiert..."

if [ -d $source_dir ]; then
	echo Verzeichnis $source_dir existiert
	if [ -f $source_dir/trunk/build/REVISION ]; then
		version_lokal=`grep "Revision" < $source_dir/trunk/build/REVISION | awk '{print $2}'`
	else
		echo "Lokale Kopie existiert nicht oder ist beschädigt"
		version_lokal=0
	fi
else
	echo "Verzeichnis $source_dir wird angelegt"
	mkdir -p $source_dir
	version_lokal=0
fi


version_svn=`svn info http://josm.openstreetmap.de/svn/trunk | grep Revision | awk '{print $2}'`

echo "lokale Version: $version_lokal"
echo "aktuelle Version: $version_svn"

if [ $version_lokal -lt $version_svn ]; then
	echo "Die lokale Version ist veraltet. Aktuelle Version wird herunter geladen."
	cd $source_dir
	svn co http://josm.openstreetmap.de/svn/trunk
	echo "Kompiliere aktualisierte Version."
	ant -f $source_dir/trunk/build.xml
else
	echo "Lokale Version ist aktuell."
fi

echo "Starte JOSM Version $version_svn"
java -Xmx1024M -jar $source_dir/trunk/dist/josm-custom.jar
